"""
CRUCIBLE Hardening Tests — DIRECTIVE-NXTG-20260318-03

Targeted tests generated by the Gate 2 + Gate 5 + Gate 8 audit.
Covers:
  - Gate 2: non-empty list invariants for registries / catalog endpoints
  - Gate 5: silent exception paths now emit logs (fernet decrypt, optional auth)
  - SSRF: additional IP ranges not covered by existing tests
  - HTTP node: edge-case config and response handling
  - LLM provider registry structure invariants
"""
import logging
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from apps.orchestrator.main import (
    AppletMessage,
    HTTPRequestNodeApplet,
    ImageProviderRegistry,
    LLMProviderRegistry,
    _as_text,
    _get_fernet_encrypt,
    applet_registry,
)


# ============================================================
# Gate 2: registry and catalog non-empty invariants
# ============================================================


class TestRegistryNonEmpty:
    """Verify that core registries are always populated at module load time."""

    def test_applet_registry_non_empty(self):
        """applet_registry must contain at least the built-in node types."""
        assert isinstance(applet_registry, dict)
        assert len(applet_registry) >= 1  # Gate 2: at least one applet registered

    def test_llm_provider_registry_returns_providers(self):
        """LLMProviderRegistry.list_providers() must return ≥1 entry."""
        providers = LLMProviderRegistry.list_providers()
        assert isinstance(providers, list)
        assert len(providers) >= 1  # Gate 2: openai/anthropic/google/ollama/custom always present

    def test_llm_provider_registry_has_openai(self):
        """openai must always be in the provider list."""
        names = {p.name for p in LLMProviderRegistry.list_providers()}
        assert "openai" in names

    def test_llm_provider_registry_has_anthropic(self):
        """anthropic must always be in the provider list."""
        names = {p.name for p in LLMProviderRegistry.list_providers()}
        assert "anthropic" in names

    def test_llm_provider_registry_each_entry_has_name(self):
        """Every provider entry must have a non-empty name field."""
        providers = LLMProviderRegistry.list_providers()
        for p in providers:
            assert p.name, f"Provider entry missing name: {p}"

    def test_llm_provider_registry_configured_field_is_bool(self):
        """Each provider's 'configured' flag must be a bool (not None)."""
        providers = LLMProviderRegistry.list_providers()
        for p in providers:
            assert isinstance(p.configured, bool), f"Provider {p.name}: configured={p.configured!r}"

    def test_applet_registry_contains_llm(self):
        """The 'llm' node type must be registered."""
        assert "llm" in applet_registry

    def test_applet_registry_contains_http_request(self):
        """The 'http_request' node type must be registered (N-18)."""
        assert "http_request" in applet_registry


# ============================================================
# Gate 5: fernet decrypt no-longer-silent path
# ============================================================


class TestFernetDecryptLogging:
    """Gate 5: verify that decrypt failures emit a debug log instead of being silent."""

    def test_decrypt_invalid_token_logs_debug(self):
        """Decrypting a tampered token must log at DEBUG level, not swallow silently.

        The project uses a custom JSON handler (bypasses caplog), so we patch
        the module-level logger directly and assert it was called.
        """
        import apps.orchestrator.main as _main
        enc, dec = _get_fernet_encrypt()
        with patch.object(_main.logger, "debug") as mock_debug:
            result = dec("not-valid-base64-fernet-token!!!")
        assert result is None
        mock_debug.assert_called_once()
        call_msg = str(mock_debug.call_args)
        assert "fernet" in call_msg.lower() or "decrypt" in call_msg.lower()

    def test_decrypt_empty_string_returns_none(self):
        """Empty string is not valid ciphertext; must return None without raising."""
        enc, dec = _get_fernet_encrypt()
        result = dec("")
        assert result is None

    def test_encrypt_then_decrypt_roundtrip(self):
        """Encrypt/decrypt round-trip must recover the original plaintext."""
        enc, dec = _get_fernet_encrypt()
        plaintext = "api-key-secret-value"
        assert dec(enc(plaintext)) == plaintext

    def test_decrypt_wrong_key_returns_none(self):
        """Ciphertext from a different key instance must return None, not raise."""
        enc, dec = _get_fernet_encrypt()
        # Encrypt with one key instance, then use _dec from a second call
        # Both calls use the same module-level FERNET_CIPHER, so this tests a
        # corrupted token rather than a different key.
        enc2, dec2 = _get_fernet_encrypt()
        token = enc("secret")
        # Corrupt one byte in the middle to simulate tampered ciphertext
        token_bytes = bytearray(token.encode())
        token_bytes[len(token_bytes) // 2] ^= 0xFF
        corrupted = token_bytes.decode("latin-1")
        result = dec2(corrupted)
        assert result is None


# ============================================================
# SSRF: additional IP ranges not in existing test_node_applets.py
# ============================================================


class TestSSRFAdditionalRanges:
    """Gate 2 / SSRF hardening: IP ranges and hostnames not covered by prior tests."""

    @pytest.fixture
    def applet(self):
        return HTTPRequestNodeApplet()

    def _msg(self, url: str) -> AppletMessage:
        return AppletMessage(
            content={},
            context={},
            metadata={"node_data": {"url": url, "method": "GET"}},
        )

    @pytest.mark.asyncio
    async def test_ssrf_ipv6_loopback_blocked(self, applet):
        """IPv6 loopback ::1 must be blocked."""
        result = await applet.on_message(self._msg("http://[::1]/admin"))
        assert "error" in result.content
        assert "blocked" in result.content["error"].lower()

    @pytest.mark.asyncio
    async def test_ssrf_link_local_169_blocked(self, applet):
        """169.254.x.x link-local (AWS metadata) must be blocked."""
        result = await applet.on_message(self._msg("http://169.254.169.254/latest/meta-data/"))
        assert "error" in result.content
        assert "blocked" in result.content["error"].lower()

    @pytest.mark.asyncio
    async def test_ssrf_dot_local_hostname_blocked(self, applet):
        """*.local hostnames (mDNS) must be blocked."""
        result = await applet.on_message(self._msg("http://mymachine.local/"))
        assert "error" in result.content
        assert "blocked" in result.content["error"].lower()

    @pytest.mark.asyncio
    async def test_ssrf_dot_internal_hostname_blocked(self, applet):
        """*.internal hostnames must be blocked."""
        result = await applet.on_message(self._msg("http://db.internal/query"))
        assert "error" in result.content
        assert "blocked" in result.content["error"].lower()

    @pytest.mark.asyncio
    async def test_ssrf_public_hostname_not_blocked(self, applet):
        """Public hostnames (api.example.com) must NOT be blocked by SSRF check."""
        # The static method should return False for public names.
        # We test the method directly — no network call.
        assert HTTPRequestNodeApplet._is_ssrf_blocked("https://api.example.com/v1") is False

    def test_ssrf_172_31_blocked(self, applet):
        """172.31.x.x is within the 172.16-31 private range — must be blocked."""
        assert HTTPRequestNodeApplet._is_ssrf_blocked("http://172.31.0.1/") is True

    def test_ssrf_malformed_url_returns_false(self):
        """Malformed URLs must not raise; the caller rejects them at the HTTP layer."""
        result = HTTPRequestNodeApplet._is_ssrf_blocked("not-a-url-at-all")
        assert result is False  # no host component → not blocked at SSRF level

    def test_ssrf_empty_url_returns_false(self):
        """Empty string URL must not raise."""
        result = HTTPRequestNodeApplet._is_ssrf_blocked("")
        assert result is False


# ============================================================
# HTTP node: edge-case config validation
# ============================================================


class TestHTTPNodeConfigEdgeCases:
    """Edge cases in HTTPRequestNodeConfigModel not covered by existing tests."""

    @pytest.fixture
    def applet(self):
        return HTTPRequestNodeApplet()

    def _msg(self, node_data: dict) -> AppletMessage:
        return AppletMessage(content={}, context={}, metadata={"node_data": node_data})

    @pytest.mark.asyncio
    async def test_unsupported_method_returns_error(self, applet):
        """An unsupported HTTP method (TRACE) should produce a validation error."""
        msg = self._msg({"url": "https://api.example.com/", "method": "TRACE"})
        result = await applet.on_message(msg)
        assert "error" in result.content

    @pytest.mark.asyncio
    async def test_whitespace_only_url_returns_error(self, applet):
        """A URL consisting of only whitespace must trigger validation error."""
        msg = self._msg({"url": "   ", "method": "GET"})
        result = await applet.on_message(msg)
        assert "error" in result.content

    @pytest.mark.asyncio
    async def test_delete_method_accepted(self, applet):
        """DELETE method must be accepted and issued."""
        import httpx
        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 204
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/resource/1"
        mock_resp.headers = {"content-type": "text/plain"}
        mock_resp.text = ""
        mock_resp.json.side_effect = ValueError("no body")

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(return_value=mock_resp)
            mock_cls.return_value = mock_client

            msg = self._msg({"url": "https://api.example.com/resource/1", "method": "DELETE"})
            result = await applet.on_message(msg)

        assert result.content.get("ok") is True
        assert result.content.get("status_code") == 204

    @pytest.mark.asyncio
    async def test_put_method_with_json_body(self, applet):
        """PUT with a JSON body must serialize body and set content-type."""
        import httpx
        captured = {}

        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/resource/1"
        mock_resp.headers = {"content-type": "application/json"}
        mock_resp.text = '{"updated": true}'
        mock_resp.json.return_value = {"updated": True}

        async def capture_request(*args, **kwargs):
            captured.update(kwargs)
            return mock_resp

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(side_effect=capture_request)
            mock_cls.return_value = mock_client

            msg = self._msg({
                "url": "https://api.example.com/resource/1",
                "method": "PUT",
                "body_template": {"name": "updated"},
                "body_type": "json",
            })
            result = await applet.on_message(msg)

        assert result.content.get("ok") is True
        assert result.content.get("status_code") == 200

    @pytest.mark.asyncio
    async def test_zero_retries_no_retry_on_5xx(self, applet):
        """With max_retries=0, a single 500 must be returned immediately (no retry)."""
        import httpx
        call_count = 0

        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 500
        mock_resp.is_success = False
        mock_resp.url = "https://api.example.com/fail"
        mock_resp.headers = {"content-type": "text/plain"}
        mock_resp.text = "Internal Server Error"
        mock_resp.json.side_effect = ValueError("not JSON")

        async def always_500(*args, **kwargs):
            nonlocal call_count
            call_count += 1
            return mock_resp

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(side_effect=always_500)
            mock_cls.return_value = mock_client

            msg = self._msg({"url": "https://api.example.com/fail", "method": "GET", "max_retries": 0})
            result = await applet.on_message(msg)

        assert call_count == 1
        assert result.content.get("ok") is False
        assert result.content.get("status_code") == 500


# ============================================================
# HTTP node: api_key query_param auth type
# ============================================================


class TestHTTPNodeAPIKeyHeader:
    """api_key auth type injects key into a custom header."""

    @pytest.fixture
    def applet(self):
        return HTTPRequestNodeApplet()

    def _msg(self, node_data: dict) -> AppletMessage:
        return AppletMessage(content={}, context={}, metadata={"node_data": node_data})

    @pytest.mark.asyncio
    async def test_api_key_custom_header_injected(self, applet):
        """api_key auth_type must inject key into the named header."""
        import httpx
        captured_kwargs = {}

        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/data"
        mock_resp.headers = {"content-type": "application/json"}
        mock_resp.text = '{"ok": true}'
        mock_resp.json.return_value = {"ok": True}

        async def capture(*args, **kwargs):
            captured_kwargs.update(kwargs)
            return mock_resp

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(side_effect=capture)
            mock_cls.return_value = mock_client

            msg = self._msg({
                "url": "https://api.example.com/data",
                "method": "GET",
                "auth_type": "api_key",
                "auth_value": "my-api-key-value",
                "auth_header_name": "X-Custom-Key",
            })
            result = await applet.on_message(msg)

        headers = captured_kwargs.get("headers", {})
        assert headers.get("X-Custom-Key") == "my-api-key-value", (
            f"Expected X-Custom-Key in request headers, got: {headers}"
        )
        assert result.content.get("ok") is True

    @pytest.mark.asyncio
    async def test_unknown_auth_type_ignored(self, applet):
        """An unsupported auth_type string must not cause an error — just skip auth injection."""
        import httpx

        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/data"
        mock_resp.headers = {"content-type": "application/json"}
        mock_resp.text = '{"result": "ok"}'
        mock_resp.json.return_value = {"result": "ok"}

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(return_value=mock_resp)
            mock_cls.return_value = mock_client

            msg = self._msg({
                "url": "https://api.example.com/data",
                "method": "GET",
                "auth_type": "none",
            })
            result = await applet.on_message(msg)

        assert result.content.get("ok") is True


# ============================================================
# Image provider registry invariants (Gate 2)
# ============================================================


class TestImageProviderRegistry:
    """ImageProviderRegistry must always be non-empty."""

    def test_image_provider_list_non_empty(self):
        providers = ImageProviderRegistry.list_providers()
        assert isinstance(providers, list)
        assert len(providers) >= 1  # Gate 2: openai/stability/flux always registered

    def test_image_provider_has_openai(self):
        names = {p.name for p in ImageProviderRegistry.list_providers()}
        assert "openai" in names

    def test_image_provider_each_entry_has_name(self):
        for p in ImageProviderRegistry.list_providers():
            assert p.name

    def test_image_provider_configured_field_is_bool(self):
        for p in ImageProviderRegistry.list_providers():
            assert isinstance(p.configured, bool)


# ============================================================
# _as_text helper — used by all applets to coerce content
# ============================================================


class TestAsTextHelper:
    """_as_text must coerce any input to a non-None string."""

    def test_string_passthrough(self):
        assert _as_text("hello") == "hello"

    def test_none_returns_empty(self):
        result = _as_text(None)
        assert isinstance(result, str)

    def test_dict_returns_string(self):
        result = _as_text({"key": "value"})
        assert isinstance(result, str)
        assert len(result) > 0

    def test_list_returns_string(self):
        result = _as_text([1, 2, 3])
        assert isinstance(result, str)

    def test_integer_returns_string(self):
        result = _as_text(42)
        assert isinstance(result, str)
        assert "42" in result

    def test_empty_string_preserved(self):
        result = _as_text("")
        assert isinstance(result, str)


# ============================================================
# HTTP node: response header capture behaviour
# ============================================================


class TestHTTPNodeResponseHeaders:
    """Verify include_response_headers flag controls output."""

    @pytest.fixture
    def applet(self):
        return HTTPRequestNodeApplet()

    def _msg(self, node_data: dict) -> AppletMessage:
        return AppletMessage(content={}, context={}, metadata={"node_data": node_data})

    @pytest.mark.asyncio
    async def test_headers_included_by_default(self, applet):
        """include_response_headers=True (default) should include headers in output."""
        import httpx
        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/"
        mock_resp.headers = {"content-type": "application/json", "x-rate-limit": "100"}
        mock_resp.text = '{"ok": true}'
        mock_resp.json.return_value = {"ok": True}

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(return_value=mock_resp)
            mock_cls.return_value = mock_client

            msg = self._msg({"url": "https://api.example.com/", "method": "GET"})
            result = await applet.on_message(msg)

        assert "headers" in result.content

    @pytest.mark.asyncio
    async def test_headers_excluded_when_disabled(self, applet):
        """include_response_headers=False should omit headers from output."""
        import httpx
        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/"
        mock_resp.headers = {"content-type": "application/json"}
        mock_resp.text = '{"ok": true}'
        mock_resp.json.return_value = {"ok": True}

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(return_value=mock_resp)
            mock_cls.return_value = mock_client

            msg = self._msg({
                "url": "https://api.example.com/",
                "method": "GET",
                "include_response_headers": False,
            })
            result = await applet.on_message(msg)

        assert "headers" not in result.content


# ============================================================
# HTTP node: successful request populates last_http_response context
# ============================================================


class TestHTTPNodeContextPropagation:
    """Verify last_http_response is written to output context."""

    @pytest.fixture
    def applet(self):
        return HTTPRequestNodeApplet()

    @pytest.mark.asyncio
    async def test_last_http_response_in_context(self, applet):
        """A successful HTTP call must populate context['last_http_response']."""
        import httpx
        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/data"
        mock_resp.headers = {"content-type": "application/json"}
        mock_resp.text = '{"result": 42}'
        mock_resp.json.return_value = {"result": 42}

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(return_value=mock_resp)
            mock_cls.return_value = mock_client

            msg = AppletMessage(
                content={},
                context={"run_id": "test-run"},
                metadata={"node_data": {"url": "https://api.example.com/data", "method": "GET"}},
            )
            result = await applet.on_message(msg)

        assert "last_http_response" in result.context
        lr = result.context["last_http_response"]
        assert lr["status_code"] == 200
        assert lr["ok"] is True

    @pytest.mark.asyncio
    async def test_original_context_preserved(self, applet):
        """Existing context keys must be preserved after HTTP call."""
        import httpx
        mock_resp = MagicMock(spec=httpx.Response)
        mock_resp.status_code = 200
        mock_resp.is_success = True
        mock_resp.url = "https://api.example.com/"
        mock_resp.headers = {"content-type": "text/plain"}
        mock_resp.text = "pong"
        mock_resp.json.side_effect = ValueError("not json")

        with patch("apps.orchestrator.main.httpx.AsyncClient") as mock_cls:
            mock_client = AsyncMock()
            mock_client.__aenter__ = AsyncMock(return_value=mock_client)
            mock_client.__aexit__ = AsyncMock(return_value=False)
            mock_client.request = AsyncMock(return_value=mock_resp)
            mock_cls.return_value = mock_client

            msg = AppletMessage(
                content={},
                context={"custom_key": "custom_value"},
                metadata={"node_data": {"url": "https://api.example.com/", "method": "GET"}},
            )
            result = await applet.on_message(msg)

        assert result.context.get("custom_key") == "custom_value"
